// Generated by scripts/generate-runtime-helper.mjs from runtime helper ABI v1.
// Source SHA-256: d1a6b960405fad1da869b081aac018695b28372341cad8a077caa645310f32ef
// Edit packages/runtime/src/helpers/v1.js, then regenerate.
export function syncDeferBody(
  names: Record<'stack' | 'failed' | 'failure' | 'cleanup' | 'error', string>,
): string {
  return (
    '\n  let ' +
    names.failed +
    ' = false,\n    ' +
    names.failure +
    ';\n  while (' +
    names.stack +
    '?.length) {\n    const ' +
    names.cleanup +
    ' = ' +
    names.stack +
    '.pop();\n    if (' +
    names.cleanup +
    ') {\n      try {\n        ' +
    names.cleanup +
    '();\n      } catch (' +
    names.error +
    ') {\n        ' +
    names.failed +
    ' = true;\n        ' +
    names.failure +
    ' = ' +
    names.error +
    ';\n      }\n    }\n  }\n  if (' +
    names.failed +
    ') throw ' +
    names.failure +
    ';\n'
  );
}
